name: EasyRules
main: net.gamesketch.bukkit.easy.core
version: 0.0.1
website: http://www.gamesketch.net
author: The GameSketch Community
description: >
             Rules + pages, simplyfied
commands:
  rules:
    description: A page with rules
    usage: |
           /<command> pagename
           Example: /<command> - Shows the list with pages
           Example: /<command> building - Shows the rules about building (if configured)